Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,9 @@ jobs:
           rm yarn.lock
 
       - name: Install dependencies
-        run: yarn install --immutable
+        run: |
+          yarn install
+          yarn install --immutable || { echo "Installation with --immutable failed, retrying without..." && yarn install; }
 
       - name: Build Strapi (if necessary)
         run: yarn build
